make ghcr package public

diff --git a/.github/workflows/pkg-kcreposcanner.yml b/.github/workflows/pkg-kcreposcanner.yml
--- a/.github/workflows/pkg-kcreposcanner.yml
+++ b/.github/workflows/pkg-kcreposcanner.yml
@@ -70,3 +70,15 @@ jobs:
           TAGS: ${{ steps.meta.outputs.tags }}
           DIGEST: ${{ steps.build-and-push.outputs.digest }}
         run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
+
+      - name: Make package public
+        if: ${{ github.event_name != 'pull_request' }}
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          package_url=$(gh api "/orgs/CaseyLabs/packages?package_type=container" --jq '.[] | select(.name == "kcutils/kcreposcanner") | .url' | head -n 1)
+          if [ -z "$package_url" ]; then
+            printf '%s\n' 'failed to locate kcRepoScanner package url' >&2
+            exit 1
+          fi
+          gh api -X PATCH "$package_url" -H "Accept: application/vnd.github.package-deletes-preview+json" -f visibility=public
